name: linux-x64-cpu-gcc
on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
concurrency:
  group: linux-x64-cpu-gcc-${{ github.ref }}
  cancel-in-progress: true
permissions:
  contents: read

jobs:
  linux-gcc:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: update
      run: sudo apt update
    - name: install_dep
      run: sudo apt install libgtk2.0-dev
    - name: install_conan
      run: | 
        pip3 install conan
        conan profile detect --force
    - name: build
      run: |
        mkdir build
        conan install . --build=missing -pr:h=docker/x86_gcc_profile
        cd build
        cmake ..
        make -j 2
    - name: test
      run: cd  build && pwd && test/graph_validation_test