name: macos-x86-cpu-clang
on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
    - '.github/workflows/macos-x86-cpu-clang.yml'
    - 'CMakeLists.txt'
    - 'cmake/**'
    - 'mediapipe/**'
    - 'examples/**'
  pull_request:
    branches: [ main ]
    paths:
    - '.github/workflows/macos-x86-cpu-clang.yml'
    - 'CMakeLists.txt'
    - 'cmake/**'
    - 'mediapipe/**'
    - 'examples/**'
concurrency:
  group: macos-x86-cpu-clang-${{ github.ref }}
  cancel-in-progress: true
env:
  DEVELOPER_DIR: /Applications/Xcode_13.4.1.app/Contents/Developer
  MAC_DEPLOYMENT_TARGET: '10.9'
  MAC_ARM64_DEPLOYMENT_TARGET: '11.0'
  ENABLE_BITCODE: OFF
  ENABLE_ARC: OFF
  ENABLE_VISIBILITY: OFF
permissions:
  contents: read

jobs:
  macos-clang:
    runs-on: macos-12
    steps:
    - uses: actions/checkout@v3
    - name: install_conan
      run: | 
        pip3 install conan
        conan profile detect --force
    - name: build
      run: |
        rm /usr/local/Cellar/cmake/3.27.3/share/cmake/Modules/Findprotobuf.cmake
        mkdir build
        conan install . --build=missing 
        cd build
        cmake ..
        make -j 2
    - name: test
      run: cd  build && make test